### ISSUE TITLE
Docker compilation is broken

### ISSUE THREAD

**Issue by waghanza** [ringabout/httpx#29]
Hi @ringabout,

I'm not using `nim` on a day to day basis, but seems that some could use containers to compile `nim`'s code.

However, the following version
 https://github.com/ringabout/httpx/blob/a3a2a9f65ac6fb3a3153e5379d561d99079e0402/httpx.nimble#L13
is not available, so compilation using containers could be broken.

Regards,

**Comment by waghanza** [comment]
cc @ire4ever1190

**Comment by ire4ever1190** [comment]
Thanks for bringing that up :+1: hopefully the PR is merged soon
