### ISSUE TITLE
Application crashes With empty header

### ISSUE THREAD

**Issue by toghrulgasimov** [ringabout/httpx#8]
https://github.com/xflywind/httpx/blob/3c00013f966b70b6c5fd198a26a0a17875295390/src/httpx.nim#L254

**Comment by toghrulgasimov** [comment]
Example command : `nc ip port`

**Comment by ringabout** [comment]
Related: 
https://github.com/dom96/httpbeast/issues/42
https://github.com/dom96/httpbeast/pull/67

feel free to make a PR to backport the change
